/lower_tracking_mpc_node:
  ros__parameters:
    batch_supervision: false
    duty_topic: /control/duty_cmd
    enable_output_filter: false
    goal_reached_topic: /planner/goal_reached
    input_timeout_sec: 0.6
    lower_controller_rate_hz: 10.0
    lower_enable_steering_actuator_model: false
    lower_max_steering_angle_rad: 0.3
    lower_max_steering_rate_radps: 1.0471975512
    lower_min_effective_speed_mps: 0.1
    lower_min_path_spacing_m: 0.05
    lower_path_timeout_sec: 1.5
    lower_prediction_dt_sec: 0.1
    lower_prediction_steps: 20
    lower_q_heading: 0.5
    lower_q_lateral: 1.0
    lower_r_steering: 0.3
    lower_rd_steering_rate: 8.0
    lower_reference_path_topic: /planner/lower_reference_path
    lower_steering_actuator_delay_sec: 0.2
    lower_steering_actuator_time_constant_sec: 0.85
    lower_use_path_arclength: true
    mavlink_auto_arm: false
    mavlink_auto_manual_mode: false
    mavlink_bind_ip: 0.0.0.0
    mavlink_bind_port: 14540
    mavlink_disarm_on_shutdown: true
    mavlink_enable: true
    mavlink_force_arm: false
    mavlink_hold_last_valid_sec: 0.0
    mavlink_keepalive_rate_hz: 20.0
    mavlink_send_neutral_on_invalid: true
    mavlink_source_component: 190
    mavlink_source_system: 245
    mavlink_steer_sign: 1.0
    mavlink_target_component: 1
    mavlink_target_system: 1
    mavlink_throttle_max_norm: 0.09
    max_virtual_brake: 0.7
    max_virtual_throttle: 0.09
    odom_topic: /motive/vehicle/odom_map
    odom_yaw_is_orientation_z: true
    path_change_reset_threshold_m: 0.75
    pixhawk_output_backend: mavlink_udp
    pose_invert_x: false
    pose_invert_y: false
    pose_jump_reset_threshold_m: 1.0
    pose_max_dt_for_speed: 0.5
    pose_position_scale: 1.0
    pose_speed_lpf_alpha: 1.0
    pose_stamped_topic: /px4/sih/odom
    pose_stamped_yaw_is_orientation_z: true
    pose_swap_xy: false
    pose_x_offset: 0.0
    pose_y_offset: 0.0
    pose_yaw_offset_rad: 0.0
    publish_applied_cmd_when_invalid: true
    publish_pwm: true
    pwm_center: 1500
    pwm_max: 2000
    pwm_min: 1000
    pwm_topic: /cmd_pwm
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    reset_on_path_change: false
    reset_topic: /controller/reset
    scale_mode: fullscale
    solver_hold_last_valid_sec: 0.0
    speed_deadband_mps: 0.03
    speed_integral_limit: 0.5
    speed_ki: 0.01
    speed_kp: 0.08
    state_input_type: odom
    steer_norm_lpf_alpha: 0.7
    steer_norm_max: 1.0
    steer_norm_rate_max: 1.5
    steer_sign: 1.0
    steering_pwm_max: 2000
    steering_pwm_min: 1000
    target_accel_mps2: 0.0
    target_speed_mps: 6.0
    throttle_ff: 0.05
    throttle_pwm_max: 2000
    throttle_pwm_min: 1500
    use_sim_time: false
    virtual_cmd_topic: /cmd_control
    wheelbase: 2.8

