/upper_planner_node:
  ros__parameters:
    a_max_mps2: 1.0
    allow_topic_path_override_when_csv_loaded: false
    bev_forward_m: 34.0
    csv_global_path_file: local_map.csv
    enable_waypoint_bias: false
    expected_grid_frame_id: Vehicle
    global_path_topic: /navigation/global_path
    goal_reached_topic: /planner/goal_reached
    goal_stop_distance_m: 0.5
    grid_map_topic: /bev/occupancy_grid
    grid_positive_is_drivable: false
    grid_value_threshold: 1
    input_timeout_sec: 3.0
    lambda_position: 1.0
    lambda_relative_turn: 0.9
    lower_min_path_spacing_m: 0.05
    lower_prediction_dt_sec: 0.1
    lower_reference_path_topic: /planner/lower_reference_path
    max_steering_angle_rad: 0.3
    miqp_big_m: 100.0
    miqp_binary_diagonal_regularization: 0.0001
    miqp_diagonal_regularization: 1.0e-10
    miqp_feasibility_tolerance: 0.001
    normalize_upper_input_cost: false
    odom_topic: /motive/vehicle/odom_map
    odom_yaw_is_orientation_z: true
    path_frame_id: map
    pose_invert_x: false
    pose_invert_y: false
    pose_max_dt_for_speed: 0.5
    pose_position_scale: 1.0
    pose_speed_lpf_alpha: 1.0
    pose_stamped_topic: /px4/sih/odom
    pose_stamped_yaw_is_orientation_z: true
    pose_swap_xy: false
    pose_x_offset: 0.0
    pose_y_offset: 0.0
    pose_yaw_offset_rad: 0.0
    position_scale_m: 10.0
    preview_grid_reserve_steps: 1
    preview_interval_boundary_margin_m: 2.0
    preview_interval_debug: false
    preview_interval_enable_nominal_fallback: true
    preview_interval_fallback_max_centering_length_m: 9.0
    preview_interval_nominal_fallback_width_m: 4.5
    preview_interval_relative_length_factor: 1.5
    preview_interval_soft_ratio: 0.7
    preview_limit_to_grid_extent: true
    preview_line_sample_m: 0.1
    preview_min_segment_samples: 2
    preview_min_target_distance_m: 0.1
    preview_restore_full_horizon: true
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    relative_turn_scale_rad: 0.3490658504
    require_grid_frame_match: true
    require_grid_map: true
    reset_waypoint_on_path_update: false
    scale_mode: fullscale
    state_input_type: odom
    target_speed_mps: 6.0
    terminal_buffer_max_turn_rad: 0.3490658504
    terminal_position_weight_multiplier: 1000.0
    turn_preview_steps: 2
    turn_weight_growth: 2.0
    upper_planner_rate_hz: 2.0
    upper_prediction_dt_sec: 1.0
    upper_preview_steps: 10
    upper_r_dpsi: 1.0
    upper_r_dv: 1.0
    upper_sparse_path_topic: /planner/upper_path_sparse
    use_csv_global_path: false
    use_sim_time: false
    vehicle_length_m: 4.7
    waypoint_x_bias_m: 0.0
    waypoint_y_bias_m: 0.0
    waypoint_yaw_bias_rad: 0.17
    wheelbase: 2.8
    wp_switch_eps: 10.0
    wp_switch_max_distance_m: 15.0

